### PR TITLE
Excel2yaml improvements

### PR DESCRIPTION
**Pull request by maxwelllevin**
This PR totally refactors the excel2yaml script, making it more flexible and adding it as a CLI tool to the tsdat-tools command. The excel template has also been improved with added colors/formatting.

## Screenshots:

<details><summary>Instructional Sheet</summary>

image

</details> 

<details><summary>Dataset Metadata Template</summary>

image

</details> 

<details><summary>Independent Variables Template</summary>

image

</details> 

<details><summary>Dependent Variables Template</summary>

image

</details> 

## TODOs:
- [x] Add logging to CLI
- [x] Add descriptions of metadata to template
- [x] Add CLI command to make a copy of the template
- [X] Add CLI command to convert excel to yaml files

## Considerations / Caveats

* This now requires installing tsdat-tools, whereas the old method provided the jupyter notebook and all the python code so you could just run it without installing much. This is an OK change, as the new libraries required by tsdat-tools are mostly covered when you would have installed tsdat.
* This does not produce a `pipeline.yaml` file; that still needs to be made by an ingest developer. This is because the `pipeline.yaml` file requires precise paths to the other config files relative to the pipeline repository root (e.g., `path: pipelines/lidar_sta/config/dataset.yaml`), which seems difficult to get right without adding extra complexity to the instructions or scripts. Better to just do it manually.

### CODE REVIEW

**Comment by maxwelllevin** [comment]
@mkieburtzpnnl @jmcvey3 please review at your convenience.

**Comment by maxwelllevin** [comment]
Feedback from @mkieburtzpnnl:

## Instructions sheet:
- [x] Tsdat should be capitalized.
 
- [x] We’re going to give this to PIs right? So maybe a more descriptive sentence about why this process is useful to us: “A time consuming part of developing new pipelines is creating the dataset configuration file. By filling this form out, you enable the ingest developer to spend more time writing the ingest itself. A command line utility is used to convert this excel sheet into the dataset configuration file.”
 
In the independent/dependent details, when the different columns are being described:

- [x] For new name, let’s say “please use underscores instead of spaces” instead of just recommending that they do that. Since we don’t allow spaces in variable names.
- [x] For datatype, can we say what the options are?
- [x] For units, it should say what a unitless variable should have: “1”
- [x] In the dependent variable details, there’s a font change between standard name and min/max value descriptions
- [ ] The independent and dependent variables are part of the input data file. I think the independent vars description is good. The dependent one can be really short. “The Dependent Variables sheet lists the dependent variables in this dataset. These will appear in the ‘measurements’ tab on the Wind Data Hub dataset page.” Something like that. And saying that the independent variables will appear under the ‘dimensions’ tab on the website would be good too.
- [x] I feel like we don’t need steps 2 and 3 in the instructions part of the sheet. That can be documented somewhere else and could potentially confuse PIs thinking they have to do those steps.
 

- [x] Since you’re used to the nitpicks by now: the term key-value pair is more common than key-item pair.
 
- [x] I went to the ARM standards to get inspiration to rewrite the definition of a long name: “A clear and concise description of the variable. Imagine using this as the label on a plot.” For example. Wordsmith away.
 
- [x] Add a note saying Standard name is required if the variable is a primary measurement.
 

## Metadata page:

- [ ] I’m thinking that this should only be for custom metadata aka global attributes. We already get the title, name, location etc from the cookie cutter template, which isn’t going away.
 
### Independent variables

- [ ] The example timezone should be UTC
- [ ] I see in all of our WFIP3 pipelines, we have the long name for the time var as “UTC time”. Similarly, for the units they are “Seconds since 1970-01-01 00:00:00 UTC”
I think it’s a little weird that “original unit” for the time variable has an example of the time format in the input file. I feel like it should just say N/A and it’s the developer’s job to find the time format and put it in the retriever.
- [x] I feel like the ‘new’ names/units column should be to the left of the original name/units column.
 
### Dependent variables

- [x] As minor as it gets: is “wind_speed_from_direction” really the right standard name for wind_direction?
- [x] Also as minor as it gets: the cnr long name should be “Carrier to noise ratio”
- [x] Let’s have a primary measurement column in here. That isn’t used for making the config files but once the metadata is uploaded, it lets the developer go in there and mark the primary measurements. Primary measurements require a standard name so that can be said somewhere.
- [x] I feel like the ‘new’ names/units should be to the left of the original name/units.

**Comment by jmcvey3** [comment]
Great refactor Max! The one thing I see is that the timezone in the output dataset.yaml file should be UTC, no matter what the given input timezone is.

**Comment by mkieburtzpnnl** [comment]
Tested the script, it worked great, I couldn't find any bugs. I agree with James, the output timezone is always UTC. Maybe the timezone column in the independent variable should be 'original timezone' to signal that there needs to be a timezone conversion?

**Comment by jmcvey3** [comment]
> Tested the script, it worked great, I couldn't find any bugs. I agree with James, the output timezone is always UTC. Maybe the timezone column in the independent variable should be 'original timezone' to signal that there needs to be a timezone conversion?

I believe that's the way I originally had it set, maybe got lost in translation

**Comment by mkieburtzpnnl** [comment]
I feel like the original timezone also shouldn't be a column, but just a box somewhere, where they can change it if needed.

**Comment by maxwelllevin** [comment]
Okay, updated the template to include most of the suggested edits. There are a few things I didn't implement:


> These will appear in the ‘measurements’ tab on the Wind Data Hub dataset page.” Something like that. And saying that the independent variables will appear under the ‘dimensions’ tab on the website would be good too

This is a tsdat tool, so I hesitate to add text specific for A2E projects. 


> **Metadata Page:**  I’m thinking that this should only be for custom metadata aka global attributes. We already get the title, name, location etc from the cookie cutter template, which isn’t going away.

I want to keep these global attributes in to ensure that the yaml produced by this tool is valid, even without the cookiecutter. I think it would be nice to get some PI feedback on how to identify the ingest. The developer can still adjust the info as desired.

> I see in all of our WFIP3 pipelines, we have the long name for the time var as “UTC time”. Similarly, for the units they are “Seconds since 1970-01-01 00:00:00 UTC”
I think it’s a little weird that “original unit” for the time variable has an example of the time format in the input file. I feel like it should just say N/A and it’s the developer’s job to find the time format and put it in the retriever.

> I feel like the original timezone also shouldn't be a column, but just a box somewhere, where they can change it if needed.

I changed the way the time independent variable is handled, since it is a bit different than the others and we already know what the standardized unit and other things are for it. I think this makes things a bit cleaner.

image

**Pull request merged**
